server:
  port: 9595

spring:
  application:
    name: hospital-review-client
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      