server:
  port: 5050
  
spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name:   com.mysql.cj.jdbc.Driver
    
logging:
  level:
    '[org.springframework.security]': debug 
