server:
  port: 2025
spring:
  application:
    name: zuul-api-gateway
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  host:
    socket-timeout-millis:  2000000     
    connect-timeout-millis: 2000000
  routes:
    lab-service:
      path: /lab-service/**
      url: http://localhost:3030
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 10000  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"