

spring:
  application:
    name: feign-review-client
     
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
      
server:
  port: 8686
  
