#myapp.bean.address = create
#logging.level.org.springframework.boot=trace

spring:
  config:
    activate:
      on-profile:
      - "test"
      
server:
  port: 5050
  
---
spring:
  config:
    activate:
      on-profile:
      - "prod"
      
server:
  port: 6060

