#myapp.bean.address = create
#logging.level.org.springframework.boot=trace

spring:
  application:
    name: hospital-info-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root  
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer2:8781/eureka,http://eureka-peer1:8771/eureka
      
      
---
spring:
  config:
    activate:
      on-profile:
      - "test"
      
server:
  port: 5050
  
---
spring:
  config:
    activate:
      on-profile:
      - "prod"
      
server:
  port: 6060

