
spring:
  application:
    name: eureka-registry

  config:
    activate:
      on-profile:
      - default
server:
  port: 8761
  
    

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka      
---

spring:
  application:
    name: eureka-registry

  config:
    activate:
      on-profile:
      - peer1
server:
  port: 8771
  
    

eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-registry
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer2:8781/eureka/      

      
---

spring:
  application:
    name: eureka-registry

  config:
    activate:
      on-profile:
      - peer2
server:
  port: 8781
  
    

eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-registry
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer1:8771/eureka/      

      


      