

spring:
  application:
    name: hospital-review-service
  config:
    activate:
      on-profile:
      - "dev"
  boot:
    admin:
      client:
        url:
        - http://localhost:7878
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      
      
server:
  port: 5050
  
---
  

spring:
  application:
    name: hospital-review-service
  config:
    activate:
      on-profile:
      - "prod"

  boot:
    admin:
      client:
        url:
        - http://localhost:7878
     
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 5055
  